export const selectsArray = [
    {
        title: 'Число',
        date: [
            {number: '01'},
            {number: '02'},
            {number: '03'},
            {number: '04'},
            {number: '05'},
            {number: '06'},
            {number: '07'},
            {number: '08'},
            {number: '09'},
            {number: '10'},
            {number: '11'},
            {number: '12'},
            {number: '13'},
            {number: '14'},
            {number: '15'},
            {number: '16'},
            {number: '17'},
            {number: '18'},
            {number: '19'},
            {number: '20'},
            {number: '21'},
            {number: '22'},
            {number: '23'},
            {number: '24'},
            {number: '25'},
            {number: '26'},
            {number: '27'},
            {number: '28'},
            {number: '29'},
            {number: '30'},
            {number: '31'},
        ]
    },
    {
        title: 'Місяць',
        date: [
            {number: '01'},
            {number: '02'},
            {number: '03'},
            {number: '04'},
            {number: '05'},
            {number: '06'},
            {number: '07'},
            {number: '08'},
            {number: '09'},
            {number: '10'},
            {number: '11'},
            {number: '12'},
        ]
    },
    {
        title: 'Час',
        date: [
            {number: '8:15'},
            {number: '9:25'},
            {number: '9:45'},
            {number: '10:35'},
            {number: '11:35'},
            {number: '13:05'},
        ]
    },
]